create table if not exists public.betrayal_rankings (
  id bigint generated by default as identity primary key,
  nickname text not null,
  score integer not null,
  kills integer not null,
  alive integer not null,
  boss_hp_left integer not null,
  boss_hp_max integer not null,
  end_reason text not null,
  win boolean not null default false,
  play_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint betrayal_rankings_nickname_check check (
    char_length(nickname) between 2 and 12
    and nickname !~ '[[:space:]]'
  ),
  constraint betrayal_rankings_score_check check (score between 0 and 999999),
  constraint betrayal_rankings_kills_check check (kills between 0 and 9999),
  constraint betrayal_rankings_alive_check check (alive between 0 and 20),
  constraint betrayal_rankings_boss_hp_left_check check (boss_hp_left between 0 and 1000000),
  constraint betrayal_rankings_boss_hp_max_check check (boss_hp_max between 1 and 1000000),
  constraint betrayal_rankings_end_reason_check check (char_length(end_reason) <= 32)
);

create unique index if not exists betrayal_rankings_daily_nickname_idx
  on public.betrayal_rankings (play_date, nickname);

create index if not exists betrayal_rankings_daily_score_idx
  on public.betrayal_rankings (play_date, score desc, created_at asc);

alter table public.betrayal_rankings enable row level security;

drop policy if exists "betrayal rankings are readable" on public.betrayal_rankings;
create policy "betrayal rankings are readable"
  on public.betrayal_rankings
  for select
  to anon, authenticated
  using (true);

create or replace function public.submit_betrayal_score(
  p_nickname text,
  p_score integer,
  p_kills integer,
  p_alive integer,
  p_boss_hp_left integer,
  p_boss_hp_max integer,
  p_end_reason text,
  p_win boolean,
  p_play_date date
)
returns public.betrayal_rankings
language plpgsql
security definer
set search_path = public
as $$
declare
  submitted public.betrayal_rankings;
begin
  p_nickname := regexp_replace(coalesce(p_nickname, ''), '[[:space:]]', '', 'g');

  if char_length(p_nickname) < 2 or char_length(p_nickname) > 12 then
    raise exception 'invalid nickname';
  end if;

  if p_play_date < ((now() at time zone 'Asia/Seoul')::date - 1)
     or p_play_date > ((now() at time zone 'Asia/Seoul')::date + 1) then
    raise exception 'invalid play date';
  end if;

  insert into public.betrayal_rankings (
    nickname,
    score,
    kills,
    alive,
    boss_hp_left,
    boss_hp_max,
    end_reason,
    win,
    play_date
  )
  values (
    p_nickname,
    p_score,
    p_kills,
    p_alive,
    p_boss_hp_left,
    p_boss_hp_max,
    p_end_reason,
    p_win,
    p_play_date
  )
  on conflict (play_date, nickname)
  do update set
    score = excluded.score,
    kills = excluded.kills,
    alive = excluded.alive,
    boss_hp_left = excluded.boss_hp_left,
    boss_hp_max = excluded.boss_hp_max,
    end_reason = excluded.end_reason,
    win = excluded.win,
    updated_at = now()
  where excluded.score > betrayal_rankings.score
  returning * into submitted;

  if submitted is null then
    select *
      into submitted
      from public.betrayal_rankings
      where play_date = p_play_date
        and nickname = p_nickname;
  end if;

  return submitted;
end;
$$;

revoke all on function public.submit_betrayal_score(text, integer, integer, integer, integer, integer, text, boolean, date) from public;
grant execute on function public.submit_betrayal_score(text, integer, integer, integer, integer, integer, text, boolean, date) to anon, authenticated;
